### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by randomuser10800** [MrBukLau/mp3tag-web-sources-scripts#3]
Hey, is it possible for you to add synced lyrics, thanks!

Edit: Also for some artists, their profile picture aren't showing up.

**Comment by MrBukLau** [comment]
Sorry for the late response. Unfortunately, I do not think that Apple allows people to use their API to retrieve time-synced song lyrics. Regarding the profile pictures, I also have that same issue, but I think that it might be Apple's fault that the pictures do not show up for some artists on your device.
