### ISSUE TITLE
Can't find metadata

### ISSUE THREAD

**Issue by ScarlettHaze** [MrBukLau/mp3tag-web-sources-scripts#4]
The scripts not working anymore I think it's because of the Apple Music update.

**Comment by MrBukLau** [comment]
Yep. Apple updated their Apple Music website, which caused the Apple Music script not to work right now. All we can do is wait for someone to find a new way to get the metadata or for Apple to undo their changes to the website.

**Comment by egxl** [comment]
> 

At the moment the iTunes script still works, hope that helps.

**Comment by ScarlettHaze** [comment]
Maybe something like this would help fix things. Since they have worked out how to grab the data here. https://github.com/ToadKing/apple-music-barcode-isrc

**Comment by MrBukLau** [comment]
The Apple Music script is now working.
